# Generated by Django 5.1.1 on 2024-10-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_init_email_customer_init_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='init_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
